fail_fast: true
repos:
  - repo: local
    hooks:
      - id: incr_version
        name: incr_version
        entry: incr_version
        language: python
        language_version: python3
        pass_filenames: false
        args: ['-f', 'src/incr_version/__version__.py']
      - id: ruff-check
        name: ruff-check
        entry: ruff
        args: ['check', '--fix']
        language: system
        types: [python]
        stages: [commit]
      - id: ruff-format
        name: ruff-format
        entry: ruff
        args: [format]
        language: system
        types: [python]
        stages: [commit]
